from toontown.coghq.SpecImports import *
import random 
from toontown.toonbase import ToontownGlobals
CogParent2 = 10000
FrontCogParent2 = 11000
BattlePlace4 = 1400001
BattlePlace3 = 11000
BattleCellId2 = 2
Battle3CellId = 3
CogParent = 100007
CogParent1 = 100009
BattlePlace1 = 100004
BattlePlace2 = 100005
BattleCellId = 0
BattleCellId1 = 1
BattleCells = {BattleCellId2: {'parentEntId': BattlePlace4,
                'pos': Point3(0, 0, 0)},
 Battle3CellId: {'parentEntId': FrontCogParent2,
                     'pos': Point3(0, 0, 0)},
 BattleCellId: {'parentEntId': BattlePlace1,
                'pos': Point3(0, 0, 0)},
 BattleCellId1: {'parentEntId': BattlePlace2,
                 'pos': Point3(0, 0, 0)}}
CogData = [{'parentEntId': CogParent2,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11]), 
  'battleCell': BattleCellId2,
  'pos': Point3(-8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11]),
  'battleCell': BattleCellId2,
  'pos': Point3(-3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11]),
  'battleCell': BattleCellId2,
  'pos': Point3(3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11]),
  'battleCell': BattleCellId2,
  'pos': Point3(8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent2,
  'boss': 0,
  'level': random.choice([6, 7, 8, 9]),
  'battleCell': Battle3CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent2,
  'boss': 0,
  'level': random.choice([6, 7, 8, 9]),
  'battleCell': Battle3CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent2,
  'boss': 0,
  'level': random.choice([6, 7, 8, 9]),
  'battleCell': Battle3CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent2,
  'boss': 0,
  'level': random.choice([6, 7, 8, 9]),
  'battleCell': Battle3CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
  {'parentEntId': CogParent,
  'boss': 0,
  'level': ToontownGlobals.CashbotMintCogLevel,
  'battleCell': BattleCellId,
  'pos': Point3(-8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': ToontownGlobals.CashbotMintCogLevel + 1,
  'battleCell': BattleCellId,
  'pos': Point3(-3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': ToontownGlobals.CashbotMintCogLevel,
  'battleCell': BattleCellId,
  'pos': Point3(3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': ToontownGlobals.CashbotMintCogLevel + 1,
  'battleCell': BattleCellId,
  'pos': Point3(8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': ToontownGlobals.CashbotMintCogLevel,
  'battleCell': BattleCellId1,
  'pos': Point3(-8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': ToontownGlobals.CashbotMintCogLevel + 1,
  'battleCell': BattleCellId1,
  'pos': Point3(-3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': ToontownGlobals.CashbotMintCogLevel,
  'battleCell': BattleCellId1,
  'pos': Point3(3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': ToontownGlobals.CashbotMintCogLevel + 1,
  'battleCell': BattleCellId1,
  'pos': Point3(8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1}]
ReserveCogData = []