from toontown.coghq.SpecImports import *
import random
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_11/models/lawbotHQ/LB_Zone15b',
        'wantDoors': 1},
 1001: {'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': None,
        'requestSave': None},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 100030: {'type': 'battleBlocker',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(44.257774353, 0.0, 0.0),
          'hpr': Vec3(0.0, 0.0, 0.0),
          'scale': Vec3(1, 1, 1),
          'cellId': 0,
          'radius': 25.0},
 100000: {'type': 'elevatorMarker',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(45, -0.313949, 0),
          'hpr': Vec3(-90, 0, 0),
          'scale': Point3(1, 1, 1),
          'modelPath': 0},
 10000: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Point3(270.0, 0.0, 0.0),
         'scale': 1}}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0],
 'titleString': 'MemTag: LawbotOfficeOilRoom_Battle00 %s' % random.random()}
