from panda3d.core import *
from . import TTLocalizer
import random
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_12/models/bossbotHQ/BossbotFairwayRoom_A',
        'wantDoors': 1},
 1001: {'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': {'entType': 'door',
                             'username': 'rurbino',
                             'parentEntId': 110001,
                             'entId': 110002},
        'requestSave': None},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 110200: {'type': 'battleBlocker',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(0, 40, 0),
          'hpr': Point3(270, 0, 0),
          'scale': Vec3(1, 1, 1),
          'cellId': 0,
          'radius': 20},
 120200: {'type': 'battleBlocker',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(0, -40, 0),
          'hpr': Point3(270, 0, 0),
          'scale': Vec3(1, 1, 1),
          'cellId': 1,
          'radius': 20},
 120000: {'type': 'model',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 2.5,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_12/models/bossbotHQ/ttap_m_ara_bhq_cogGolfRoofTower.bam'},
 1202000: {'type': 'model',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(85.1512, -52.4203, 0.025),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1.0,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_12/models/bossbotHQ/ttap_m_ara_bhq_cogGolfFlagBlue.bam'},
 110202: {'type': 'door',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(0, 0, 0),
          'hpr': Vec3(0, 0, 0),
          'scale': 1,
          'color': Vec4(1, 1, 1, 1),
          'isLock0Unlocked': 1,
          'isLock1Unlocked': 1,
          'isLock2Unlocked': 1,
          'isLock3Unlocked': 1,
          'isOpen': 0,
          'isOpenEvent': 0,
          'isVisBlocker': 0,
          'secondsOpen': 1,
          'unlock0Event': 0,
          'unlock1Event': 0,
          'unlock2Event': 0,
          'unlock3Event': 0},
 10002: {'type': 'nodepath',
         'name': 'props',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10003:  {'type': 'apBarrel', # ARCHI BARREL PLACEMENT
          'name': 'archi',
          'comment': '',
          'parentEntId': 10002,
          'pos': Point3(31.42, -72.9, 0.025),
          'hpr': Vec3(-140, 0, 0),
          'scale': Vec3(1, 1, 1),
          'apRewardIndex': 0,
          'rewardPerGrab': 15,
          'rewardPerGrabMax': 0},
 110001: {'type': 'nodepath',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(101.07, 0, 0),
          'hpr': Point3(270, 0, 0),
          'scale': Vec3(1, 1, 1)}}

"""
GlobalEntities[180000] = {'type': 'healBarrel',
          'name': 'healBuddy',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(0, 0, 0.0),
          'hpr': Vec3(0, 0, 0),
          'scale': Vec3(1, 1, 1),
          'rewardPerGrab': 16,
          'rewardPerGrabMax': 16}

GlobalEntities[180001] = {'type': 'healBarrel',
          'name': 'healBuddy',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(0, 0, 0.0),
          'hpr': Vec3(0, 0, 0),
          'scale': Vec3(1, 1, 1),
          'rewardPerGrab': 16,
          'rewardPerGrabMax': 16}

GlobalEntities[180002] = {'type': 'healBarrel',
          'name': 'healBuddy',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(0, 0, 0.0),
          'hpr': Vec3(0, 0, 0),
          'scale': Vec3(1, 1, 1),
          'rewardPerGrab': 16,
          'rewardPerGrabMax': 16}


GlobalEntities[16000] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_couchA.bam'}

GlobalEntities[16001] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_couchA.bam'}

GlobalEntities[16002] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cab.bam'}

GlobalEntities[16003] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cab.bam'}

GlobalEntities[16004] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_endtableA.bam'}

GlobalEntities[16005] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_torch_lampA.bam'}

GlobalEntities[16006] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_torch_lampA.bam'}

GlobalEntities[16007] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_pottedplantA.bam'}

GlobalEntities[16008] = {'type': 'model',
         'name': 'middle',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1,
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_11/models/lawbotHQ/LB_CardBoardBox.bam'}




GlobalEntities[180010] = {'type': 'healBarrel',
          'name': 'archi',
          'comment': '',
          'parentEntId': 1000,
          'pos': Point3(0, 0, 0.0),
          'hpr': Vec3(0, 0, 0),
          'scale': Vec3(1, 1, 1),
          'rewardPerGrab': 10,
          'rewardPerGrabMax': 10}

"""